name: objectory
version: 0.3.16
author: Vadim Tsushko <vadimtsushko@gmail.com>
description: Object document mapper/persistency layer for server-side and browser apps
homepage: https://github.com/vadimtsushko/objectory
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  browser: '>=0.9.0 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
  mongo_dart: any
  mongo_dart_query: any
dev_dependencies:
  args: '>=0.9.0 <0.10.0'
  hop: any
  stream: any
  unittest: '>=0.9.0 <0.10.0'
